### ISSUE TITLE
Error 302 redirect

### ISSUE THREAD

**Issue by wernight** [Narrat/cli-google#2]
```
$ google test
https://www.google.com/search?&ie=UTF-8&oe=UTF-8&q=test
Server responded with an error: 302
```

**Comment by Narrat** [comment]
Hmm... strange.
Thanks for reporting. This is new. A week ago there was no redirect

**Comment by Narrat** [comment]
It seems they're now redirecting from .com to the local variants (like .de)

Fix on the way
